"""Build the paper package from experiment results (``neurostias report``).

Everything here is read from experiments/*/results/{summary.json,provenance.json,*.csv}
and copied or reformatted; no number is typed by hand. Outputs in paper/:

* tables/<E##>_*.csv and .tex       - copies of key result tables (+ LaTeX)
* figures/                          - copies of experiment figures (PNG + PDF)
* results_overview.md               - one section per experiment with its key table
* methods_draft.md                  - datasets, software versions, parameters, seeds (from provenance)
* reproducibility.md                - commands to regenerate everything
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
PAPER = ROOT / "paper"

KEY_TABLES = {
    "E01": ["e01_summary.csv", "e01_paired_tests.csv", "e01_ari_by_donor.csv"],
    "E02": ["e02a_summary.csv", "e02a_paired_tests.csv", "e02a_registration_qc.csv", "e02b_best_3d_graph.csv",
            "e02b_degree_matched.csv", "e02c_merfish_class_coherence.csv"],
    "E03": ["e03_summary_semi_synthetic.csv"],
    "E04": ["e04a_merfish_metrics.csv", "e04b_dlpfc_layers_summary.csv"],
    "E05": ["e05a_null_summary.csv", "e05b_power_summary_semi_synthetic.csv"],
    "E06": ["e06_canonical_recall_summary.csv", "e06_replication_summary.csv"],
    "E07": ["e07a_maturation_vs_age.csv", "e07a_posthoc_neuron_fraction.csv", "e07_selection_check.csv",
            "e07b_stage_annotation.csv", "e07c_region_annotation.csv"],
    "E08": ["e08a_agreement.csv", "e08b_eegbci_summary.csv"],
    "E09": ["e09_hh_fi.csv", "e09_lif_fi.csv", "e09_brunel_summary.csv"],
    "E10": ["e10_agreement_vs_neurom.csv", "e10_classification.csv"],
    "E11": ["e11_classification.csv", "e11_graph_metric_tests.csv"],
    "E12": ["e12_summary.csv"],
}


def _md(df: pd.DataFrame) -> str:
    def fmt(v):
        return f"{v:.3f}" if isinstance(v, float) else str(v)
    cols = list(df.columns)
    lines = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    lines += ["| " + " | ".join(fmt(v) for v in r) + " |" for r in df.itertuples(index=False)]
    return "\n".join(lines)


def build() -> Path:
    (PAPER / "tables").mkdir(parents=True, exist_ok=True)
    (PAPER / "figures").mkdir(parents=True, exist_ok=True)
    overview = ["# Results overview (auto-generated)", "",
                "Generated by `neurostias report` from `experiments/*/results`. Edit the experiments, not this file.", ""]
    methods = ["# Methods draft (auto-generated from provenance)", ""]
    datasets: dict[str, dict] = {}
    packages: dict[str, str] = {}
    for exp_dir in sorted((ROOT / "experiments").glob("E*_*")):
        eid = exp_dir.name.split("_")[0]
        res = exp_dir / "results"
        sfile = res / "summary.json"
        if not sfile.exists():
            overview += [f"## {exp_dir.name}", "", "*Not run yet.*", ""]
            continue
        s = json.loads(sfile.read_text())
        prov = json.loads((res / "provenance.json").read_text()) if (res / "provenance.json").exists() else {}
        overview += [f"## {eid}: {s.get('title', '')}", "", f"**Question.** {s.get('question', '')}", "",
                     f"Data origin: **{s.get('data_origin')}**. Runtime {s.get('runtime_seconds')} s. "
                     f"Git commit {prov.get('git', {}).get('commit', '')[:10]}"
                     f"{' (dirty working tree)' if prov.get('git', {}).get('dirty') else ''}.", ""]
        for t in KEY_TABLES.get(eid, []):
            p = res / t
            if p.exists():
                df = pd.read_csv(p)
                shutil.copy(p, PAPER / "tables" / f"{eid}_{t}")
                try:
                    df.to_latex(PAPER / "tables" / f"{eid}_{t.replace('.csv', '.tex')}", index=False, float_format="%.3f")
                except Exception:
                    pass
                overview += [f"**{t}**", "", _md(df), ""]
        for fig in sorted(res.glob("*.png")) + sorted(res.glob("*.pdf")):
            shutil.copy(fig, PAPER / "figures" / f"{eid}_{fig.name}")
        if s.get("baseline_status"):
            overview += ["Baselines: " + ", ".join(f"{k} ({v['status']})" for k, v in s["baseline_status"].items()), ""]
        for n in s.get("notes", []):
            overview.append(f"- {n}")
        overview.append("")
        for k, v in prov.get("inputs", {}).items():
            datasets[k] = {"path": v.get("path"), "sha256": v.get("sha256", "")[:16], "bytes": v.get("bytes")}
        packages.update(prov.get("packages", {}))
        methods += [f"## {eid}", "", f"Parameters: `{json.dumps(prov.get('params', {}), default=str)[:1500]}`", ""]
    methods += ["## Software", "", "| package | version |", "|---|---|"] + [f"| {k} | {v} |" for k, v in sorted(packages.items())]
    methods += ["", "Baseline tools ran in isolated environments; exact versions are in "
                "`benchmarks/envs/baselines_freeze.txt` and `benchmarks/envs/brian2_freeze.txt`.", "",
                "## Input files (SHA-256 prefix)", "", "| input | sha256 | bytes |", "|---|---|---|"]
    methods += [f"| {k} | {v['sha256']} | {v['bytes']} |" for k, v in sorted(datasets.items())]
    (PAPER / "results_overview.md").write_text("\n".join(overview))
    (PAPER / "methods_draft.md").write_text("\n".join(methods))
    (PAPER / "reproducibility.md").write_text("\n".join([
        "# Reproducing all results", "", "```bash", "./install.sh full", "source .venv/bin/activate",
        "neurostias data fetch all          # downloads + checksums (local datasets must be provided)",
        "bash benchmarks/envs/setup_baselines.sh   # isolated baseline environments",
        "neurostias experiment all", "neurostias report", "```", "",
        "Each experiment writes provenance.json (input SHA-256, git commit, parameters, seeds, package versions)."]))
    print(f"paper package written to {PAPER}")
    return PAPER
